In [1]:
import torch

In [3]:
x = torch.arange(12)

In [4]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
x.reshape(-1, 6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [ ]:
z = torch.zeros((2, 3, 4))

In [13]:
z

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
z.shape

torch.Size([2, 3, 4])

In [15]:
z.numel()

24

In [16]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [17]:
torch.randn(3, 4)

tensor([[-0.9560, -0.3220, -0.7049, -0.7723],
        [-0.2131, -0.4153, -0.5588, -0.4893],
        [ 1.7788, -0.2167,  1.4245,  0.9969]])

In [18]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [19]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [20]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [21]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [22]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [23]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [24]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [26]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))

In [27]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [29]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [30]:
Y.shape

torch.Size([3, 4])

In [31]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [33]:
Z = torch.cat((X, Y), dim=1)

In [34]:
Z

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [35]:
Z.shape

torch.Size([3, 8])

In [36]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [37]:
X.sum()

tensor(66.)

In [38]:
a = torch.arange(3).reshape((3, 1))

In [39]:
a

tensor([[0],
        [1],
        [2]])

In [40]:
b = torch.arange(2).reshape((1, 2))

In [41]:
b

tensor([[0, 1]])

In [42]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [43]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [44]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [46]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [47]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [48]:
X[1, 2] = 9

In [49]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [50]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [51]:
X[0:2, :] = 12


In [52]:
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [53]:
before = id(Y)

In [54]:
before

5208455024

In [55]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [56]:
Y = Y + X

In [57]:
id(Y)

5379325360

In [58]:
Z = torch.zeros_like(Y)

In [59]:
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [60]:
id(Z)

5234490160

In [61]:
Z[:] = X + Y

In [62]:
id(Z)

5234490160

In [63]:
A = X.numpy()

In [64]:
A

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [65]:
B = torch.tensor(A)

In [66]:
B

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [67]:
type(A)

numpy.ndarray

In [68]:
type(B)

torch.Tensor

In [69]:
a = torch.tensor([3.5])

In [70]:
a

tensor([3.5000])

In [71]:
a.item()

3.5

In [72]:
float(a)

3.5

In [73]:
int(a)

3