In [1]:
import torch

In [2]:
A = torch.arange(20).reshape(4, 5)

In [3]:
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [4]:
X = torch.arange(24).reshape(2, 3, 4)

In [5]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [6]:
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [7]:
A.shape

torch.Size([4, 5])

In [9]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

In [10]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [12]:
A.sum(axis=0)

tensor([40., 45., 50., 55.])

In [14]:
sum_A = A.sum(axis=1, keepdim=True)

In [17]:
A.sum(axis=1).shape

torch.Size([5])

In [18]:
sum_A.shape

torch.Size([5, 1])

In [21]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [19]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [20]:
A.sum(axis=0, keepdim=True)

tensor([[40., 45., 50., 55.]])

In [22]:
y = torch.ones(4, dtype = torch.float32)

In [23]:
y

tensor([1., 1., 1., 1.])

In [ ]:
x = torch.arange(4)

In [27]:
x

tensor([0, 1, 2, 3])

In [31]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [32]:
A.shape

torch.Size([5, 4])

In [33]:
B = torch.ones(4, 3)

In [34]:
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [36]:
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])