In [1]:
import torch

In [2]:
x = torch.arange(4.0)

In [3]:
x

tensor([0., 1., 2., 3.])

In [5]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [6]:
x.grad

In [9]:
torch.dot(x, x)

tensor(14., grad_fn=<DotBackward0>)

In [7]:
y = 2 * torch.dot(x, x)

In [8]:
y

tensor(28., grad_fn=<MulBackward0>)

In [10]:
y.backward()

In [13]:
x.grad

tensor([ 0.,  4.,  8., 12.], grad_fn=<MulBackward0>)

In [14]:
x.grad == 4 * x

tensor([True, True, True, True])

In [16]:
x.grad.zero_()

tensor([0., 0., 0., 0.], grad_fn=<ZeroBackward0>)

In [17]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [18]:
y = x.sum()

In [19]:
y

tensor(6., grad_fn=<SumBackward0>)

In [20]:
y.backward()

In [21]:
y


tensor(6., grad_fn=<SumBackward0>)

In [22]:
x.grad

tensor([1., 1., 1., 1.], grad_fn=<ZeroBackward0>)