In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l


In [3]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [7]:
def load_array(data_arrays, batch_size, is_train=True): #@save
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels) , batch_size)


In [9]:
next(iter(data_iter))

[tensor([[ 0.2519, -0.5454],
         [ 0.6952, -0.3431],
         [-0.2077,  1.5058],
         [-1.0466, -0.9492],
         [-0.5949, -0.6020],
         [ 1.3386,  0.5218],
         [ 0.5857,  0.1271],
         [-0.7521,  0.2801],
         [ 0.7173, -0.6600],
         [ 0.2700,  0.8753]]),
 tensor([[ 6.5474],
         [ 6.7679],
         [-1.3263],
         [ 5.3483],
         [ 5.0635],
         [ 5.0972],
         [ 4.9476],
         [ 1.7268],
         [ 7.8886],
         [ 1.7645]])]

In [10]:
true_w

tensor([ 2.0000, -3.4000])

In [11]:
true_b

4.2

In [12]:
from torch import nn

In [13]:
net = nn.Sequential(nn.Linear(2, 1))

In [14]:
net[0].weight.data.normal_(0, 0.01)

tensor([[-0.0011,  0.0108]])

In [15]:
net[0].bias.data.fill_(0)

tensor([0.])

In [16]:
loss = nn.MSELoss()

In [17]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [18]:
num_epochs = 3

In [25]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000100
epoch 2, loss 0.000098
epoch 3, loss 0.000098


In [26]:
w = net[0].weight.data

In [27]:
w

tensor([[ 1.9999, -3.3997]])

In [28]:
true_w

tensor([ 2.0000, -3.4000])

In [29]:
print('w的估计误差：', true_w - w.reshape(true_w.shape))

w的估计误差： tensor([ 0.0001, -0.0003])


In [30]:
b = net[0].bias.data

In [31]:
b

tensor([4.2002])

In [32]:
true_b

4.2

In [33]:
print('b的估计误差：', true_b - b)

b的估计误差： tensor([-0.0002])
